public class ControleProdutos {
    public static void main(String[] args) {
    
    String nomeDoSmartphone = "SamsungA10s";
    String marcaDoSmartphone = "Samsung";
    double precoDoSmartphone = 1200.00;
    Integer quantidadeEstoqueSmartphone = 2;
    
    String nomeDoLaptop= "SamsungBook2";
    String marcaDoLaptop = "Samsung";
    double precoDoLaptop = 4000.00;
    Integer quantidadeEstoqueLaptop = 4;
    
    String nomeDoFoneDeOuvidoBluetooth= "FoneJBL";
    String marcaDoFoneDeOuvidoBluetooth = "JBL";
    double precoDoFoneDeOuvidoBluetooth = 200.00;
    Integer quantidadeFoneDeOuvidoBluetooth = 15;
    
    System.out.println("Smartphone");
    System.out.println("Dados do Smartphone:");
    System.out.println("Nome: " + nomeDoSmartphone);
    System.out.println("Marca: " + marcaDoSmartphone);
    System.out.println("Preco: " + precoDoSmartphone);
    System.out.println("Quantidade: " + quantidadeEstoqueSmartphone);
    
    System.out.println("Laptop");
    System.out.println("Dados do Laptop:");
    System.out.println("Nome: " + nomeDoLaptop);
    System.out.println("Marca: " + marcaDoLaptop);
    System.out.println("Preco: " + precoDoLaptop);
    System.out.println("Quantidade: " + quantidadeEstoqueLaptop);
    
    System.out.println("Fone de Ouvido Bluetooth");
    System.out.println("Dados do Fone de Ouvido Bluetooth:");
    System.out.println("Nome: " + nomeDoFoneDeOuvidoBluetooth);
    System.out.println("Marca: " + marcaDoFoneDeOuvidoBluetooth);
    System.out.println("Preco: " + precoDoFoneDeOuvidoBluetooth);
    System.out.println("Quantidade: " + quantidadeFoneDeOuvidoBluetooth);
    }
}
